# Generated by Django 3.2.3 on 2021-06-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('published_year', models.PositiveSmallIntegerField(default=2019, verbose_name='Дата издания')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('rating', models.PositiveSmallIntegerField(default=1, verbose_name='Рейтинг')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('author', models.ManyToManyField(related_name='book_director', to='books.Author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
