# Generated by Django 3.2.3 on 2021-06-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210616_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='url',
        ),
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(default='null', max_length=100, verbose_name='Имя автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_books',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество книг автора'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
