# Generated by Django 3.2.3 on 2021-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210616_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
        migrations.AddField(
            model_name='genre',
            name='number_of_genres',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество книг автора'),
        ),
    ]
