# Generated by Django 3.2.3 on 2021-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210616_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.ManyToManyField(related_name='book_author', to='books.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genre_book', to='books.Genre', verbose_name='жанры'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='number_of_genres',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество книг в жанре'),
        ),
    ]
